#pragma once

#include <ntddk.h>

#define FILE_DEVICE_RIFEZ_BRIDGE  0x00008337

#define IOCTL_RIFEZ_GET_PCM_INFO \
    CTL_CODE(FILE_DEVICE_RIFEZ_BRIDGE, 0x800, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_RIFEZ_READ_PCM \
    CTL_CODE(FILE_DEVICE_RIFEZ_BRIDGE, 0x801, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_RIFEZ_RESET_PCM \
    CTL_CODE(FILE_DEVICE_RIFEZ_BRIDGE, 0x802, METHOD_BUFFERED, FILE_READ_DATA)



typedef struct _RIFEZ_PCM_INFO
{
    ULONG SampleRate;
    ULONG Channels;
    ULONG BitsPerSample;
    ULONG BufferCapacityBytes;
    ULONG BufferedBytes;
} RIFEZ_PCM_INFO, * PRIFEZ_PCM_INFO;