// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

@SuppressWarnings("unused")
public final class CodecType {
  private CodecType() { }
  public static final byte Unknown = 0;
  public static final byte PCM = 1;

  public static final String[] names = { "Unknown", "PCM", };

  public static String name(int e) { return names[e]; }
}

