// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Envelope extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static Envelope getRootAsEnvelope(ByteBuffer _bb) { return getRootAsEnvelope(_bb, new Envelope()); }
  public static Envelope getRootAsEnvelope(ByteBuffer _bb, Envelope obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean EnvelopeBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "RFZ1"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Envelope __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte messageType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte payloadType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table payload(com.google.flatbuffers.Table obj) { int o = __offset(8); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createEnvelope(FlatBufferBuilder builder,
      byte messageType,
      byte payloadType,
      int payloadOffset) {
    builder.startTable(3);
    Envelope.addPayload(builder, payloadOffset);
    Envelope.addPayloadType(builder, payloadType);
    Envelope.addMessageType(builder, messageType);
    return Envelope.endEnvelope(builder);
  }

  public static void startEnvelope(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addMessageType(FlatBufferBuilder builder, byte messageType) { builder.addByte(0, messageType, 0); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(1, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(2, payloadOffset, 0); }
  public static int endEnvelope(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishEnvelopeBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "RFZ1"); }
  public static void finishSizePrefixedEnvelopeBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "RFZ1"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Envelope get(int j) { return get(new Envelope(), j); }
    public Envelope get(Envelope obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

