// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ErrorResponse extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static ErrorResponse getRootAsErrorResponse(ByteBuffer _bb) { return getRootAsErrorResponse(_bb, new ErrorResponse()); }
  public static ErrorResponse getRootAsErrorResponse(ByteBuffer _bb, ErrorResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ErrorResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String reason() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reasonAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer reasonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createErrorResponse(FlatBufferBuilder builder,
      int reasonOffset) {
    builder.startTable(1);
    ErrorResponse.addReason(builder, reasonOffset);
    return ErrorResponse.endErrorResponse(builder);
  }

  public static void startErrorResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addReason(FlatBufferBuilder builder, int reasonOffset) { builder.addOffset(0, reasonOffset, 0); }
  public static int endErrorResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ErrorResponse get(int j) { return get(new ErrorResponse(), j); }
    public ErrorResponse get(ErrorResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

