// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class HelloResponse extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static HelloResponse getRootAsHelloResponse(ByteBuffer _bb) { return getRootAsHelloResponse(_bb, new HelloResponse()); }
  public static HelloResponse getRootAsHelloResponse(ByteBuffer _bb, HelloResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public HelloResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String receiverName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer receiverNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer receiverNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createHelloResponse(FlatBufferBuilder builder,
      int receiverNameOffset) {
    builder.startTable(1);
    HelloResponse.addReceiverName(builder, receiverNameOffset);
    return HelloResponse.endHelloResponse(builder);
  }

  public static void startHelloResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addReceiverName(FlatBufferBuilder builder, int receiverNameOffset) { builder.addOffset(0, receiverNameOffset, 0); }
  public static int endHelloResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public HelloResponse get(int j) { return get(new HelloResponse(), j); }
    public HelloResponse get(HelloResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

