// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class HelloRequest extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static HelloRequest getRootAsHelloRequest(ByteBuffer _bb) { return getRootAsHelloRequest(_bb, new HelloRequest()); }
  public static HelloRequest getRootAsHelloRequest(ByteBuffer _bb, HelloRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public HelloRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String clientName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer clientNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer clientNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createHelloRequest(FlatBufferBuilder builder,
      int clientNameOffset) {
    builder.startTable(1);
    HelloRequest.addClientName(builder, clientNameOffset);
    return HelloRequest.endHelloRequest(builder);
  }

  public static void startHelloRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addClientName(FlatBufferBuilder builder, int clientNameOffset) { builder.addOffset(0, clientNameOffset, 0); }
  public static int endHelloRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public HelloRequest get(int j) { return get(new HelloRequest(), j); }
    public HelloRequest get(HelloRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

