// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

@SuppressWarnings("unused")
public final class Payload {
  private Payload() { }
  public static final byte NONE = 0;
  public static final byte HelloRequest = 1;
  public static final byte HelloResponse = 2;
  public static final byte PingRequest = 3;
  public static final byte PongResponse = 4;
  public static final byte StatusRequest = 5;
  public static final byte StatusResponse = 6;
  public static final byte StartStreamRequest = 7;
  public static final byte StartStreamResponse = 8;
  public static final byte DisconnectRequest = 9;
  public static final byte DisconnectResponse = 10;
  public static final byte StreamConfigRequest = 11;
  public static final byte StreamConfigResponse = 12;
  public static final byte ErrorResponse = 13;

  public static final String[] names = { "NONE", "HelloRequest", "HelloResponse", "PingRequest", "PongResponse", "StatusRequest", "StatusResponse", "StartStreamRequest", "StartStreamResponse", "DisconnectRequest", "DisconnectResponse", "StreamConfigRequest", "StreamConfigResponse", "ErrorResponse", };

  public static String name(int e) { return names[e]; }
}

