// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

@SuppressWarnings("unused")
public final class ReceiverState {
  private ReceiverState() { }
  public static final byte Unknown = 0;
  public static final byte Idle = 1;
  public static final byte Discoverable = 2;
  public static final byte Pairing = 3;
  public static final byte Connected = 4;
  public static final byte Streaming = 5;
  public static final byte Reconnecting = 6;
  public static final byte Error = 7;

  public static final String[] names = { "Unknown", "Idle", "Discoverable", "Pairing", "Connected", "Streaming", "Reconnecting", "Error", };

  public static String name(int e) { return names[e]; }
}

