// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

@SuppressWarnings("unused")
public final class SampleFormat {
  private SampleFormat() { }
  public static final byte Unknown = 0;
  public static final byte PCM16 = 1;

  public static final String[] names = { "Unknown", "PCM16", };

  public static String name(int e) { return names[e]; }
}

