// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class StatusResponse extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static StatusResponse getRootAsStatusResponse(ByteBuffer _bb) { return getRootAsStatusResponse(_bb, new StatusResponse()); }
  public static StatusResponse getRootAsStatusResponse(ByteBuffer _bb, StatusResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StatusResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte state() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String deviceName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer deviceNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer deviceNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String sourceName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sourceNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer sourceNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createStatusResponse(FlatBufferBuilder builder,
      byte state,
      int deviceNameOffset,
      int sourceNameOffset) {
    builder.startTable(3);
    StatusResponse.addSourceName(builder, sourceNameOffset);
    StatusResponse.addDeviceName(builder, deviceNameOffset);
    StatusResponse.addState(builder, state);
    return StatusResponse.endStatusResponse(builder);
  }

  public static void startStatusResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addState(FlatBufferBuilder builder, byte state) { builder.addByte(0, state, 0); }
  public static void addDeviceName(FlatBufferBuilder builder, int deviceNameOffset) { builder.addOffset(1, deviceNameOffset, 0); }
  public static void addSourceName(FlatBufferBuilder builder, int sourceNameOffset) { builder.addOffset(2, sourceNameOffset, 0); }
  public static int endStatusResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StatusResponse get(int j) { return get(new StatusResponse(), j); }
    public StatusResponse get(StatusResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

