// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class StreamConfigRequest extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static StreamConfigRequest getRootAsStreamConfigRequest(ByteBuffer _bb) { return getRootAsStreamConfigRequest(_bb, new StreamConfigRequest()); }
  public static StreamConfigRequest getRootAsStreamConfigRequest(ByteBuffer _bb, StreamConfigRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StreamConfigRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long sampleRate() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 48000L; }
  public int channels() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 2; }
  public byte sampleFormat() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 1; }
  public byte codec() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 1; }
  public long frameSamples() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 480L; }

  public static int createStreamConfigRequest(FlatBufferBuilder builder,
      long sampleRate,
      int channels,
      byte sampleFormat,
      byte codec,
      long frameSamples) {
    builder.startTable(5);
    StreamConfigRequest.addFrameSamples(builder, frameSamples);
    StreamConfigRequest.addSampleRate(builder, sampleRate);
    StreamConfigRequest.addCodec(builder, codec);
    StreamConfigRequest.addSampleFormat(builder, sampleFormat);
    StreamConfigRequest.addChannels(builder, channels);
    return StreamConfigRequest.endStreamConfigRequest(builder);
  }

  public static void startStreamConfigRequest(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addSampleRate(FlatBufferBuilder builder, long sampleRate) { builder.addInt(0, (int) sampleRate, (int) 48000L); }
  public static void addChannels(FlatBufferBuilder builder, int channels) { builder.addByte(1, (byte) channels, (byte) 2); }
  public static void addSampleFormat(FlatBufferBuilder builder, byte sampleFormat) { builder.addByte(2, sampleFormat, 1); }
  public static void addCodec(FlatBufferBuilder builder, byte codec) { builder.addByte(3, codec, 1); }
  public static void addFrameSamples(FlatBufferBuilder builder, long frameSamples) { builder.addInt(4, (int) frameSamples, (int) 480L); }
  public static int endStreamConfigRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StreamConfigRequest get(int j) { return get(new StreamConfigRequest(), j); }
    public StreamConfigRequest get(StreamConfigRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

