// automatically generated by the FlatBuffers compiler, do not modify

package RifeZ.PhoneAudio.Control;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class StreamConfigResponse extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static StreamConfigResponse getRootAsStreamConfigResponse(ByteBuffer _bb) { return getRootAsStreamConfigResponse(_bb, new StreamConfigResponse()); }
  public static StreamConfigResponse getRootAsStreamConfigResponse(ByteBuffer _bb, StreamConfigResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StreamConfigResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean accepted() { int o = __offset(4); return o != 0 && 0 != bb.get(o + bb_pos); }
  public long sampleRate() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 48000L; }
  public int channels() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 2; }
  public byte sampleFormat() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 1; }
  public byte codec() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 1; }
  public long frameSamples() { int o = __offset(14); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 480L; }
  public String reason() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reasonAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer reasonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }

  public static int createStreamConfigResponse(FlatBufferBuilder builder,
      boolean accepted,
      long sampleRate,
      int channels,
      byte sampleFormat,
      byte codec,
      long frameSamples,
      int reasonOffset) {
    builder.startTable(7);
    StreamConfigResponse.addReason(builder, reasonOffset);
    StreamConfigResponse.addFrameSamples(builder, frameSamples);
    StreamConfigResponse.addSampleRate(builder, sampleRate);
    StreamConfigResponse.addCodec(builder, codec);
    StreamConfigResponse.addSampleFormat(builder, sampleFormat);
    StreamConfigResponse.addChannels(builder, channels);
    StreamConfigResponse.addAccepted(builder, accepted);
    return StreamConfigResponse.endStreamConfigResponse(builder);
  }

  public static void startStreamConfigResponse(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addAccepted(FlatBufferBuilder builder, boolean accepted) { builder.addBoolean(0, accepted, false); }
  public static void addSampleRate(FlatBufferBuilder builder, long sampleRate) { builder.addInt(1, (int) sampleRate, (int) 48000L); }
  public static void addChannels(FlatBufferBuilder builder, int channels) { builder.addByte(2, (byte) channels, (byte) 2); }
  public static void addSampleFormat(FlatBufferBuilder builder, byte sampleFormat) { builder.addByte(3, sampleFormat, 1); }
  public static void addCodec(FlatBufferBuilder builder, byte codec) { builder.addByte(4, codec, 1); }
  public static void addFrameSamples(FlatBufferBuilder builder, long frameSamples) { builder.addInt(5, (int) frameSamples, (int) 480L); }
  public static void addReason(FlatBufferBuilder builder, int reasonOffset) { builder.addOffset(6, reasonOffset, 0); }
  public static int endStreamConfigResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StreamConfigResponse get(int j) { return get(new StreamConfigResponse(), j); }
    public StreamConfigResponse get(StreamConfigResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

